applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'departamento-lista/',
        
        views.DepartamentoListView.as_view(),
        name='departamento_list'),
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'
    ),
]

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm

class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('******estamos en el forma vlid*******')

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
    {% block content %} {% endblock content %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation(); 
    </script>
</body>
</html>

templates/home/conmon/base_home.html
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>
        {% block titulo %}

        {% endblock titulo %}
    </title>
</head>
<body>
    {% block content %}
        
    {% endblock content %}
</body>
</html>

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:emplados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
</div>

templates/inicio.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Pagina de inicio sistema empleados {% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<!-- inico de la imagen de portada -->
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/20.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static 'img/30.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Lets Rocket!</figcaption>
          </figure>
        </li>
      </ul>
    </div>
  </div>
<!-- fin de la imagen de portada -->

<!-- bloque de bienvenida -->
<div class="grid-x align-center">
  <h1 class="cell large-8" style="font-size: 25px; text-align: center;">Bienvenido al Sistema de Registro de Empelados</h1>
  <div class="cell large-7">
    <div class="callout success">
      <h5>Registra y controla empleados</h5>
      <p>It has an easy to override visual style, and is appropriately subdued. It has an easy to override visual style, and is appropriately subdued.</p>
      <a href="#">Ver empleados</a>
    </div>
  </div>
</div>
<!-- fin de bloque de bienvenida -->

{% endblock content %}

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
  Registrar Empelado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
          
            <div class="medium-6 cell">
                <label>Nombres:
                  {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                  {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                  {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                  {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>foto:
                  {{form.avatar}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>

        </form>
    </div>
</div>

{% endblock content %}

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
  Eliminar Empleado
{% endblock title %}

{% block content %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{ object.full_name }}</h1>

        <form class="cell" method="POST">{% csrf_token %}

            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  {{ object.full_name }}
{% endblock title %}

{% block content %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                {{ empleado.get_job_display }}
            </div>
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'img/20.jpg' %}">
            {% endif %}        
            <div class="card-section">
                <h4>{{ empleado.full_name }}</h4>
                <p>{{ empleado.last_name }}</p>
                <p>{{ empleado.departamento.shor_name }}</p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all %}
                      <li>{{ h.hablidad }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<h1>Detalle de un empelado {{ titulo }}</h1>
{{ empleado }}

<h3>Todos los datos:</h3>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>
<p>{{ empleado.habilidades }}</p>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>C{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                        <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}
  lista empleados por departamento
{% endblock title %}

{% block content %}
  {% include "includes/header.html" %}

  <div class="grid-container">
      <div class="grid-x">
        <div class="cell">Empleados por area:</div>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>C{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
  </div>


{% endblock content %}

<h1>Lista empelados por departamento</h1>

<ul>
    
    {% for e in object_list  %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>C{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range %}

                    
                    {% if pagina == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                    {% endif %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}